_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
                - 71
            "2":
                - 1
                - 11
                - 49
                - 55
                - 71
            "3":
                - 13
                - 23
                - 55
            "4": 3.12.4
            "5": 0.19.7
            "6": 4.43.0.dev0
            "8":
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
